### ISSUE TITLE
大佬，想请教一下，可变形卷积放在模型中的哪个位置有提升啊

### ISSUE THREAD

**Issue by XhHello** [YEARNLL/dcn-4-heads-yolov5#1]

**Comment by huangzizheng01** [comment]
你好，我添加到backbone的了C3模块前面了，具体在yolov5s.yaml文件的下面部分。如果数据集小，训练成本低，你可以多试几个位置，不过Dconv比较耗内存
backbone:
  [[-1, 1, Focus, [64, 3]],  # 0-P1/2
   [-1, 1, Conv, [128, 3, 2]],  # 1-P2/4
   [-1, 3, C3, [128]],
   **[-1, 1, DConv2, [256, 3, 2]],  # 3-P3/8**
   [-1, 9, C3, [256]],
   [-1, 1, Conv, [512, 3, 2]],  # 5-P4/16
   [-1, 9, C3, [512]],
   [-1, 1, Conv, [1024, 3, 2]],  # 7-P5/32
   [-1, 1, SPP, [1024, [5, 9, 13]]],
   [-1, 3, C3TR, [1024, False]],  # 9
  ]

**Comment by XhHello** [comment]
谢谢您的回复，在您的代码中看到了，我试了加载您放的位置没啥效果，所以来咨询了一下
